[package]
name = "f1-led-circuit-plot-2sets"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
plotters = "0.3.6"
serde_derive = "1.0.202"
serde = { version = "1.0.202", features = ["derive"] }
